#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1
CONF_FILE="/etc/yggdrasil.conf"

start_service() {
	[ -f "$CONF_FILE" ] || return 1
	procd_open_instance
	procd_set_param command /usr/sbin/yggdrasil -useconffile "$CONF_FILE"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
